Repository cloudbees/lighthouse-githubapp, pull requests merged in 2019-12, with the labels that each got.

#234 fix: lets make the GH App installation URL configurable
  go.mod
  pkg/hook/github_app.go
Labels: approved, size/S

#248 Enable DataDog APM
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/lighthouse-githubapp/values.yaml
  charts/preview/values.yaml
  go.mod
  go.sum
  main.go
  pkg/flags/flags.go
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
  pkg/util/trace_utils.go
Labels: approved, lgtm, size/M

#256 fix: add a default docker registry
  charts/lighthouse-githubapp/values.yaml
Labels: approved, size/XS

#266 feat: adding github app name to the installation response
  pkg/hook/github_app.go
Labels: approved, lgtm, size/S

#282 fix: pass in better logrus context to lighthouse
  go.mod
  go.sum
  pkg/flags/flags.go
  pkg/hook/hook.go
Labels: approved, size/S
