Repository cloudbees/lighthouse-githubapp, pull requests merged in 2019-11, with the labels that each got.

#107 fix: add API to create a GH App go-scm client
  README.md
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/lighthouse-githubapp/templates/secret.yaml
  charts/lighthouse-githubapp/values.yaml
  go.mod
  pkg/flags/flags.go
  pkg/hook/scm.go
  pkg/util/urls.go
Labels: approved, size/M

#132 GitHub app repository API
  charts/lighthouse-githubapp/templates/deployment.yaml
  go.mod
  main.go
  pkg/flags/flags.go
  pkg/hook/constants.go
  pkg/hook/github_app.go
  pkg/hook/hook.go
  pkg/hook/scm.go
Labels: approved, lgtm, size/L

#157 feat: handle errors better
  pkg/hook/github_app.go
Labels: approved, lgtm, size/S

#161 feat: add additional logging
  pkg/hook/github_app.go
  pkg/hook/scm.go
Labels: approved, size/XS

#162 fix: add a debug logging for logrus
  charts/lighthouse-githubapp/templates/deployment.yaml
  main.go
  pkg/flags/flags.go
Labels: approved, lgtm, size/XS

#163 fix: add logging fields for the owner and repo
  pkg/hook/github_app.go
Labels: approved, lgtm, size/M

#165 fix: create apps scm client
  pkg/hook/github_app.go
Labels: approved, lgtm, size/M

#167 feat: remove duplicate log line
  pkg/hook/github_app.go
Labels: approved, size/XS

#168 fix: handle shutdown hook
  main.go
  pkg/hook/hook.go
  pkg/hook/scm.go
Labels: approved, lgtm, size/M

#170 fix: output correct url for an github app install
  pkg/hook/github_app.go
Labels: approved, lgtm, size/S

#171 fix: upgrade dependencies
  go.mod
  go.sum
Labels: approved, size/S

#177 fix: lets add a bot name
  Makefile
  charts/lighthouse-githubapp/values.yaml
Labels: approved, size/XS

#179 docs: polish home page
  README.md
Labels: approved, lgtm, size/S

#202 fix: upgrade jx
  pkg/hook/constants.go
Labels: approved, size/XS

#204 chore: disable wait-for-chart step as it is currently not working all…
  jenkins-x.yml
Labels: approved, lgtm, size/S

#208 fix: add a debugging REST API for install tokens
  pkg/hook/constants.go
  pkg/hook/handle_token_valid.go
  pkg/hook/helpers.go
  pkg/hook/hook.go
  pkg/hook/scm.go
Labels: approved, size/L

#219 fix: lets cache tokens for a shorter amount
  main.go
  pkg/hook/scm.go
Labels: approved, size/S

#220 fix: tidy up logging
  pkg/hook/hook.go
Labels: approved, size/M
