Repository cloudbees/lighthouse-githubapp, pull requests merged in 2019-10, with the labels that each got.

#2 fix: add missing owners file
  OWNERS
Labels: size/S

#1 feat: Add initial build files and charts
  .gitignore
  Dockerfile
  Makefile
  charts/lighthouse-githubapp/Chart.yaml
  charts/lighthouse-githubapp/Makefile
  charts/lighthouse-githubapp/templates/NOTES.txt
  charts/lighthouse-githubapp/templates/_helper.tpl
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/lighthouse-githubapp/templates/ingress.yaml
  charts/lighthouse-githubapp/templates/ksvc.yaml
  charts/lighthouse-githubapp/templates/secret.yaml
  charts/lighthouse-githubapp/templates/service.yaml
  charts/lighthouse-githubapp/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  jenkins-x.yml
  updatebot.sh
Labels: approved, size/XL

#9 fix: use correct image repo in chart
  charts/lighthouse-githubapp/values.yaml
Labels: approved, size/XS

#10 fix: deployment, lets avoid Jenkins X image replacement during rele…
  charts/lighthouse-githubapp/Makefile
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/lighthouse-githubapp/values.yaml
  charts/preview/Makefile
  charts/preview/values.yaml
Labels: approved, size/S

#11 fix: deployment, lets keep jenkins x release process performing auto …
  charts/lighthouse-githubapp/Makefile
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/preview/Makefile
  charts/preview/values.yaml
Labels: approved, size/XS

#12 fix: tidy up makefile as most of it isnt needed anymore now that jx s…
  charts/lighthouse-githubapp/Makefile
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/lighthouse-githubapp/values.yaml
  charts/preview/Makefile
  charts/preview/values.yaml
Labels: approved, size/M

#14 fix: auto deployment to the Dev environment, we need this release pip…
  jenkins-x.yml
Labels: approved, lgtm, size/S

#16 fix: moved the GitHub App token generation to the tenant service
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/lighthouse-githubapp/templates/secret.yaml
  charts/lighthouse-githubapp/values.yaml
  go.mod
  go.sum
  main.go
  pkg/flags/flags.go
  pkg/hook/hook.go
  pkg/hook/scm.go
  pkg/hook/tenant_service.go
Labels: approved, size/L

#17 docs: add diagram
  README.md
  docs/images/app.png
Labels: size/XS

#24 fix: use the SA for accessing consumer clusters
  .gitignore
  Makefile
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/lighthouse-githubapp/templates/saas-secret.yaml
  charts/lighthouse-githubapp/values.yaml
  charts/preview/values.yaml
Labels: approved, size/S

#26 fix: add wait for chart before promoting
  jenkins-x.yml
Labels: approved, size/S

#27 fix: lets add gcloud and git binaries
  Dockerfile
Labels: approved, size/XS

#30 fix: upgrade to latest lighthouse
  Dockerfile
  go.mod
  go.sum
Labels: approved, size/XS

#32 fix: pass in the consumer client factory to lighthouse
  pkg/hook/hook.go
Labels: approved, size/XS

#37 fix: upgrade lighthouse and fix up creating remote pipelines
  Makefile
  go.mod
  go.sum
  pkg/hook/connectors/cache_factory.go
  pkg/hook/connectors/factory_adapter.go
  pkg/hook/hook.go
Labels: approved, size/L

#45 fix: switch to nicer mechanism to create remote k8s connections
  charts/lighthouse-githubapp/templates/deployment.yaml
  go.mod
  go.sum
  pkg/hook/hook.go
Labels: approved, size/M

#64 fix: fix regression in lighthouse
  pkg/hook/hook.go
Labels: approved, size/S

#65 fix: fix regression in lighthouse
  pkg/hook/hook.go
Labels: approved, size/XS
