Repository cloudbees/lighthouse-githubapp, pull requests merged in 2020-03, with the labels that each got.

#571 chore: improved logging
  pkg/hook/hook.go
Labels: size/XS

#578 chore: promote to all environments
  updatebot.sh
Labels: approved, lgtm, size/XS

#589 feat: add a pipeline which scans dependencies with whitesoruce
  .whitesource.config
  jenkins-x-whitesource.yml
Labels: approved, lgtm, size/L

#593 chore: update README to test dependencies scanning with whitesource
  README.md
Labels: approved, lgtm, size/XS

#580 chore: updatebot.sh exits with a zero status
  updatebot.sh
Labels: size/XS

#603 chore: add linter script and fixes
  hack/linter.sh
  jenkins-x-lint.yml
  main.go
  pkg/hook/connectors/cache_factory.go
  pkg/hook/github_app.go
  pkg/hook/handle_webhook.go
  pkg/hook/helpers.go
  pkg/hook/hook.go
  pkg/hook/tenant_service.go
  pkg/util/trace_utils.go
  pkg/version/info.go
Labels: size/L

#606 fix: add install linter script
  hack/install_golint.sh
Labels: size/L

#631 chore: attempt to enable backoff correctly
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
Labels: size/XS

#642 chore: added extra logging for handle webhook
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
Labels: size/XS

#649 chore: log workspace & repo on webhook handling
  pkg/hook/hook.go
Labels: approved, lgtm, size/S

#653 chore: adding some logging around the token cache
  pkg/hook/constants.go
  pkg/hook/scm.go
Labels: approved, lgtm, size/S

#661 feat: log the webhook relay event
  pkg/hook/hook.go
Labels: size/XS

#667 feat: handle installation repository webhook
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
Labels: size/M

#668 chore: improve logging
  pkg/hook/hook.go
Labels: size/XS

#670 chore: log incoming hook events
  pkg/hook/hook.go
Labels: size/S

#671 chore: add extra logging to repos
  pkg/hook/hook.go
Labels: size/XS

#672 chore: use the git account link when installing app
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
Labels: size/M

#681 chore: use jx-logging
  pkg/schedulers/generator.go
Labels: approved, lgtm, size/XS

#686 chore: add a POC for webhook relaying
  pkg/hook/hook.go
Labels: approved, lgtm, size/M

#687 fix: add some extra debug logging
  pkg/hook/hook.go
Labels: size/XS

#691 chore: use the updated api for webhook relaying
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
Labels: approved, lgtm, size/S

#695 chore: add some tests around the http relay
  go.mod
  pkg/hook/handle_token_valid.go
  pkg/hook/handle_webhook.go
  pkg/hook/handle_webhook_test.go
  pkg/hook/hook.go
  pkg/hook/testdata/installation.json
  pkg/hook/testdata/installation_delete.json
  pkg/hook/testdata/push.json
  pkg/tenant/fake.go
  pkg/tenant/interface.go
  pkg/tenant/tenant_service.go
Labels: size/XL

#696 feat: calculate new signature before relaying
  pkg/hmac/generator.go
  pkg/hmac/generator_test.go
  pkg/hook/handle_webhook_test.go
  pkg/hook/hook.go
Labels: approved, lgtm, size/M

#703 fix: Retry webhook relay for "repository not configured"
  pkg/hook/handle_webhook.go
  pkg/hook/handle_webhook_test.go
  pkg/hook/hook.go
Labels: approved, lgtm, size/L

#706 fix: Recreate the signature/request/etc for each relay attempt, log more
  pkg/hook/hook.go
Labels: approved, lgtm, size/M

#707 chore: Log earlier, delay slightly on retry
  pkg/hook/hook.go
Labels: approved, lgtm, size/S

#708 fix: Retry get workspaces and relay hooks separately.
  pkg/hook/handle_webhook.go
  pkg/hook/handle_webhook_test.go
  pkg/hook/hook.go
Labels: approved, lgtm, size/L

#710 fix: Route for install check without a repository
  pkg/hook/constants.go
  pkg/hook/github_app.go
  pkg/hook/github_app_test.go
  pkg/hook/hook.go
Labels: approved, lgtm, size/L

#714 fix: Don't even try to check if repo has installation if no repo is given
  pkg/hook/github_app.go
Labels: approved, lgtm, size/S

#715 chore: add in logging around retry
  pkg/hook/hook.go
Labels: size/XS

#716 chore: log the failed attempts at webhook relaying
  main.go
  pkg/hook/hook.go
  pkg/loghelpers/logger.go
Labels: size/M

#717 chore: allow insecure webhook relaying for PR environments
  pkg/hook/hook.go
Labels: size/S

#718 chore: correcting log message around insecure logging
  pkg/hook/hook.go
Labels: size/XS

#722 chore: allow insecure relaying for version stream PRs
  pkg/hook/hook.go
Labels: approved, lgtm, size/XS

#723 fix: Pass X-GitHub-Event directly, not deduced from webhook kind
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
Labels: approved, lgtm, size/S
