Repository cloudbees/lighthouse-githubapp, pull requests merged in 2020-05, with the labels that each got.

#756 chore: require golang 1.13
  Makefile
  go.mod
  jenkins-x.yml
Labels: approved, lgtm, size/S

#878 chore: do not deploy to hornblower
  updatebot.sh
Labels: size/XS

#910 chore: add .dependabot/config.yml
  .dependabot/config.yml
Labels: size/XS

#952 chore(deps) bump linter from 1.20.0 to 1.27.0
  hack/linter.sh
Labels: approved, lgtm, size/XS

#963 chore: remove version from the index page
  go.mod
  go.sum
  pkg/hook/hook.go
Labels: approved, lgtm, size/S

#964 chore: wrap body read with a limitreader
  pkg/hook/handle_webhook.go
Labels: approved, lgtm, size/XS

#966 chore: wrap body read with a limitreader
  pkg/hook/hook.go
  pkg/util/http_utils.go
Labels: approved, lgtm, size/XS

#967 chore: use sha256 rather than sha1 for hmac signing
  pkg/hmac/generator.go
  pkg/hmac/generator_test.go
  pkg/hook/handle_webhook_test.go
  pkg/hook/hook.go
Labels: approved, lgtm, size/M

#968 chore: fix gosec issues
  hack/linter.sh
  pkg/hmac/generator.go
  pkg/hook/constants.go
  pkg/hook/handle_token_valid.go
  pkg/hook/hook.go
  pkg/hook/scm.go
Labels: approved, lgtm, size/L

#969 chore: add coverage goals to makefile
  .gitignore
  Makefile
Labels: size/XS

#976 chore: remove use of jx step credential
  jenkins-x.yml
Labels: approved, lgtm, size/M
