Repository cloudbees/lighthouse-githubapp, pull requests merged in 2020-06, with the labels that each got.

#1004 fix: remove vault paths from standard chart values
  charts/lighthouse-githubapp/templates/saas-secret.yaml
  charts/lighthouse-githubapp/templates/secret.yaml
  charts/lighthouse-githubapp/values.yaml
Labels: approved, lgtm, size/S

#1009 chore: temporarily prevent jx preview command
  charts/lighthouse-githubapp/templates/saas-secret.yaml
  charts/lighthouse-githubapp/templates/secret.yaml
  jenkins-x.yml
Labels: approved, lgtm, size/S

#1011 fix: correct typo in helm function name
  charts/lighthouse-githubapp/templates/secret.yaml
Labels: approved, lgtm, size/XS

#1016 chore: fix updatebot to promote to play
  updatebot.sh
Labels: approved, lgtm, size/XS

#1015 fix: remove vault paths from default chart values
  charts/lighthouse-githubapp/values.yaml
Labels: approved, lgtm, size/XS

#1018 chore: reenabling preview to test chart
  jenkins-x.yml
Labels: approved, lgtm, size/S

#1025 chore: remove service account config
  charts/lighthouse-githubapp/templates/deployment.yaml
  charts/lighthouse-githubapp/templates/saas-secret.yaml
  charts/lighthouse-githubapp/values.yaml
  charts/preview/values.yaml
Labels: approved, lgtm, size/S

#1029 chore: double retry time to 90s on webhook relay
  pkg/hook/hook.go
Labels: size/XS

#1038 chore: fix dependency updates
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#1039 chore: fix dependency updates
  go.mod
  go.sum
Labels: size/S, updatebot

#1073 chore: remove dependency on JX
  go.mod
  go.sum
  pkg/loghelpers/logger.go
Labels: approved, lgtm, size/XL
