Repository cloudbees/lighthouse-githubapp, pull requests merged in 2020-04, with the labels that each got.

#732 chore: assume insecure webhooks for play/staging
  pkg/hook/hook.go
  pkg/hook/hook_test.go
Labels: approved, lgtm, size/M

#742 chore: remove cache warming for kaniko
  jenkins-x.yml
Labels: approved, lgtm, size/S

#734 chore: removing unused direct lighthouse invoking
  Makefile
  go.mod
  go.sum
  hack/linter.sh
  pkg/hook/hook.go
  pkg/schedulers/builder.go
  pkg/schedulers/builder_test.go
  pkg/schedulers/config_builder.go
  pkg/schedulers/config_builder_test.go
  pkg/schedulers/generator.go
  pkg/schedulers/leaf.go
  pkg/schedulers/prow_config.go
  pkg/schedulers/test_data/merger_with_mergemethod/config.yaml
  pkg/schedulers/test_data/merger_with_mergemethod/parent.yaml
  pkg/schedulers/test_data/merger_with_mergemethod/plugins.yaml
  pkg/schedulers/test_data/merger_with_mergemethod/repo.yaml
  pkg/schedulers/test_data/merger_with_parent/config.yaml
  pkg/schedulers/test_data/merger_with_parent/parent.yaml
  pkg/schedulers/test_data/merger_with_parent/plugins.yaml
  pkg/schedulers/test_data/merger_with_parent/repo.yaml
  pkg/schedulers/test_data/multiple_contexts/config.yaml
  pkg/schedulers/test_data/multiple_contexts/plugins.yaml
  pkg/schedulers/test_data/multiple_contexts/repo.yaml
  pkg/schedulers/test_data/no_postsubmits_with_parent/config.yaml
  pkg/schedulers/test_data/no_postsubmits_with_parent/parent.yaml
  pkg/schedulers/test_data/no_postsubmits_with_parent/plugins.yaml
  pkg/schedulers/test_data/no_postsubmits_with_parent/repo.yaml
  pkg/schedulers/test_data/only_plugins/parent.yaml
  pkg/schedulers/test_data/only_plugins/plugins.yaml
  pkg/schedulers/test_data/only_plugins/repo.yaml
  pkg/schedulers/test_data/only_plugins_from_parent/parent.yaml
  pkg/schedulers/test_data/only_plugins_from_parent/plugins.yaml
  pkg/schedulers/test_data/only_plugins_from_parent/repo.yaml
  pkg/schedulers/test_data/only_plugins_from_repo/parent.yaml
  pkg/schedulers/test_data/only_plugins_from_repo/plugins.yaml
  pkg/schedulers/test_data/only_plugins_from_repo/repo.yaml
  pkg/schedulers/test_data/only_with_parent/config.yaml
  pkg/schedulers/test_data/only_with_parent/parent.yaml
  pkg/schedulers/test_data/only_with_parent/plugins.yaml
  pkg/schedulers/test_data/policy_with_parent/config.yaml
  pkg/schedulers/test_data/policy_with_parent/parent.yaml
  pkg/schedulers/test_data/policy_with_parent/plugins.yaml
  pkg/schedulers/test_data/policy_with_parent/repo.yaml
  pkg/schedulers/test_data/repo/config.yaml
  pkg/schedulers/test_data/repo/plugins.yaml
  pkg/schedulers/test_data/repo/repo.yaml
  pkg/schedulers/test_data/with_parent/config.yaml
  pkg/schedulers/test_data/with_parent/parent.yaml
  pkg/schedulers/test_data/with_parent/plugins.yaml
  pkg/schedulers/test_data/with_parent/repo.yaml
  pkg/schedulers/testhelpers/helpers.go
Labels: approved, size/XXL

#762 chore: improve logging around webhook relaying
  go.mod
  pkg/hook/hook.go
Labels: approved, lgtm, size/S

#769 chore: override stackdriver formatter
  go.mod
  go.sum
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
  pkg/loghelpers/logger.go
Labels: approved, lgtm, size/S

#774 chore: renamed 'response' to 'resp'
  pkg/hook/github_app.go
  pkg/hook/hook.go
  pkg/util/http_utils.go
Labels: approved, lgtm, size/S

#779 feat: enable tests as part of the pr build
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#784 chore: updated to use jenkins-x/logrus-stackdriver-formatter directly
  go.mod
  go.sum
  pkg/loghelpers/logger.go
Labels: approved, lgtm, size/S

#785 chore: better error handling around failing webhooks
  go.mod
  go.sum
  pkg/hook/connectors/cache_factory.go
  pkg/hook/connectors/factory_adapter.go
  pkg/hook/handle_webhook.go
  pkg/hook/hook.go
Labels: approved, lgtm, size/L

#789 chore: increase retry timeout to 45s
  pkg/hook/hook.go
Labels: approved, size/S

#788 chore: log insecure value from db
  pkg/hook/handle_webhook_test.go
  pkg/hook/hook.go
Labels: approved, size/XS

#793 chore: fixing the log statement
  pkg/hook/hook.go
Labels: approved, lgtm, size/XS

#794 chore: set the whitesource image version to 20.3.1
  jenkins-x-whitesource.yml
Labels: approved, lgtm, size/XS

#808 fix: go mods
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#854 chore: promote to arcalos-staging-mgmt
  updatebot.sh
Labels: approved, lgtm, size/XS
